#ifndef GLOBALCOLLECTIONNAMES_H
#define GLOBALCOLLECTIONNAMES_H

#include <string>


#define COLLECTIONNAME_COMMON_DIRECTIVES \
COLLECTIONNAME_DIRECTIVE(muons, Muon, 90) \
COLLECTIONNAME_DIRECTIVE(electrons, Electron, 90) \
COLLECTIONNAME_DIRECTIVE(photons, Photon, 90) \
COLLECTIONNAME_DIRECTIVE(taus, Tau, 90) \
COLLECTIONNAME_DIRECTIVE(ak4jets, Jet, 250) \
COLLECTIONNAME_DIRECTIVE(ak4jets_lowpt, CorrT1METJet, 250) \
COLLECTIONNAME_DIRECTIVE(ak8jets, FatJet, 90) \
COLLECTIONNAME_DIRECTIVE(pfmet, MET, 0) \
COLLECTIONNAME_DIRECTIVE(pfmet_raw, RawMET, 0) \
COLLECTIONNAME_DIRECTIVE(puppimet, PuppiMET, 0) \
COLLECTIONNAME_DIRECTIVE(puppimet_raw, RawPuppiMET, 0) \
COLLECTIONNAME_DIRECTIVE(metfilter, Flag, 0) \
COLLECTIONNAME_DIRECTIVE(l1prefiring, L1PreFiringWeight, 0) \
COLLECTIONNAME_DIRECTIVE(pv, PV, 0) \
COLLECTIONNAME_DIRECTIVE(isotracks, IsoTrack, 90) \
COLLECTIONNAME_DIRECTIVE(l1triggers, L1, 0) \
COLLECTIONNAME_DIRECTIVE(triggers, HLT, 0) \
COLLECTIONNAME_DIRECTIVE(triggerObjects, TrigObj, 90)

#define COLLECTIONNAME_SIM_DIRECTIVES \
COLLECTIONNAME_DIRECTIVE(pileup, Pileup, 0) \
COLLECTIONNAME_DIRECTIVE(genak4jets, GenJet, 250) \
COLLECTIONNAME_DIRECTIVE(genak8jets, GenJetAK8, 90) \
COLLECTIONNAME_DIRECTIVE(genparticles, GenPart, 250) \
COLLECTIONNAME_DIRECTIVE(lheparticles, LHEPart, 50)

#define COLLECTIONNAME_DIRECTIVES \
COLLECTIONNAME_COMMON_DIRECTIVES \
COLLECTIONNAME_SIM_DIRECTIVES


namespace GlobalCollectionNames{
  typedef unsigned int collsize_t;

#define COLLECTIONNAME_DIRECTIVE(NAME, LABEL, MAXSIZE) \
const std::string colName_##NAME(#LABEL); \
constexpr collsize_t colMaxSize_##NAME = MAXSIZE;
  COLLECTIONNAME_DIRECTIVES;
#undef COLLECTIONNAME_DIRECTIVE
}


#endif
